version: '2'
networks:
  loyalty:
    external: true
services:
  ms-iam:
    container_name: ms-iam
    image: dockerreg.local:5000/ms-iam:develop
    restart: always
    #volumes:
    #        -  /root/UM/maccess/:/opt/storage/UM/maccess
    #environment:
    #  - DB_HOST=172.16.170.108:3306
    #  - DB_USER=root
    #  - DB_PASS=asd123ASD!@#
    ports:
      - '8004:8004'
    volumes:
      - /home/fso:/fso
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.16.120.59:24224
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    networks:
      - loyalty